POST http://localhost:3000/project/layout/new/1?ownerId=tewst
Content-Type: application/json

{
  "chart": "test_12",
  "name": "Test",
  "type": "line",
  "color": "green",
  "dimension": {
    "width": 1,
    "height": 2
  },
  "index": 1,
  "icon": "person"
}