POST http://localhost:3000/project/layout/new/1?ownerId=FastStats
Content-Type: application/json

{
  "chart": "online_mode",
  "name": "Online Mode",
  "type": "pie",
  "static": true,
  "sources": [
    {
      "key": "online",
      "name": "Online",
      "color": "green",
      "value": "true"
    },
    {
      "key": "offline",
      "name": "Offline",
      "color": "red",
      "value": "false"
    }
  ],
  "dimensions": {
    "width": 2,
    "height": 1
  },
  "position": 1,
  "icon": "globe",
  "extras": {
    "donut": true,
    "brush": false
  }
}
