services:
  backend:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "5000:5000" # should match the metrics port from config
    restart: always
    volumes:
      - ./data:/app/data