CREATE TABLE IF NOT EXISTS layouts
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    options_id INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (options_id) REFERENCES layout_options (id) ON DELETE CASCADE
)