### Update settings of a project with id 1 by the specified user
PUT http://localhost:3000/projects/1?userId=test
Content-Type: application/json

{
  "private": true,
  "layout": {
    "total_servers": {
      "name": "Total Servers",
      "type": "line_chart",
      "color": "#1da1f2"
    },
    "total_players": {
      "name": "Total Players",
      "type": "line_chart",
      "color": "#1da1f2"
    },
    "online_mode": {
      "name": "Online Mode",
      "type": "pie_chart",
      "color": "#ffffff"
    },
    "server_software": {
      "name": "Server Software",
      "type": "pie_chart",
      "color": "#123456"
    }
  }
}

### Update settings of a project with id 1
PUT http://localhost:3000/projects/1
Content-Type: application/json

{
  "private": false
}