### Update settings of a project with id 1 by the specified user/org
PUT http://localhost:3000/project/settings/1?ownerId=test
Content-Type: application/json

{
  "private": true,
  "preview_chart": "total_servers",
  "project_url": "https://project.example.com",
  "icon": "gem",
  "layout": {
    "total_servers": {
      "name": "Total Servers",
      "type": "line_chart",
      "color": "#1da1f2",
      "size": 2
    },
    "total_players": {
      "name": "Total Players",
      "type": "line_chart",
      "color": "#1da1f2"
    },
    "online_mode": {
      "name": "Online Mode",
      "type": "pie_chart",
      "color": "#ffffff",
      "size": 1
    },
    "server_software": {
      "name": "Server Software",
      "type": "pie_chart",
      "color": "#123456",
      "icon": "arrow-up"
    }
  }
}

### Update settings of a project with id 1
PUT http://localhost:3000/project/settings/1
Content-Type: application/json

{
  "private": false
}