### rename project with id 1 if it is owned by a specific user/org
PUT http://localhost:3000/project/rename/1/test test test?ownerId=test

### rename project with id 1
PUT http://localhost:3000/project/rename/1/test test test